############################################################
#
# 内置 tomcat 配置
# web 访问端口号 约定 8088
#
############################################################
server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource                # 数据源类型：HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver             # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000     # 文件上传大小限制为 500kb
      max-request-size: 512000  # 请求大小限制为 500kb
  session:
    store-type: redis

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: cn.mrcode.foodiedev.pojo    # 实体层
  mapper-locations: classpath:mapper/*.xml          # mapper 层

# 通用 Mapper 配置
mapper:
  # 指定要扫描的 mapper 接口
  mappers: cn.mrcode.foodiedev.my.mapper.MyMapper
  # 在进行数据库操作的时候，判断表达式  username != null, 是否追加 username != ''
  # 这里关闭了追加，自己手写
  not-empty: false
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

debug: false
