server:
  port: 9002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
  redis:
    # 单机但实例
    database: 1
    host: 192.168.56.105
    port: 6379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ali-oss:
  # 在你创建的 bucket 概览页面里面有 Endpoint（地域节点） 信息，找其种一个即可
  endpoint: oss-cn-beijing.aliyuncs.com
  access-key-id: xO3yYN9aK6l8j4nK
  access-key-secret: xxx
  bucket: mrcode-test
  # 图片访问地址，也在概览页里面有
  host: https://mrcode-test.oss-cn-beijing.aliyuncs.com/
